# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0003_user_files_user_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_files',
            name='user_uploaded',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
