# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0005_auto_20171007_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_files',
            old_name='user_shared',
            new_name='from_user',
        ),
        migrations.AddField(
            model_name='share_files',
            name='to_user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
