# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0006_auto_20171007_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_files',
            old_name='files',
            new_name='select_file',
        ),
        migrations.RenameField(
            model_name='share_files',
            old_name='to_user',
            new_name='select_user',
        ),
    ]
