# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Box', '0007_auto_20171008_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_files',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_files',
            name='user_uploaded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
