# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0008_auto_20171105_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='share_files',
        ),
    ]
